/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 * 
 * NOTE: Manually generated after direct forge create deployment
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
    31337: {
        ZeroKlue: {
            address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
            abi: [
                {
                    type: "constructor",
                    inputs: [{ name: "_verifier", type: "address", internalType: "address" }],
                    stateMutability: "nonpayable",
                },
                {
                    type: "function",
                    name: "NUM_PUBLIC_INPUTS",
                    inputs: [],
                    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "balanceOf",
                    inputs: [{ name: "student", type: "address", internalType: "address" }],
                    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "getVerification",
                    inputs: [{ name: "student", type: "address", internalType: "address" }],
                    outputs: [
                        { name: "verifiedAt", type: "uint256", internalType: "uint256" },
                        { name: "ephemeralPubkey", type: "bytes32", internalType: "bytes32" },
                        { name: "age", type: "uint256", internalType: "uint256" },
                    ],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "isExpiringSoon",
                    inputs: [
                        { name: "student", type: "address", internalType: "address" },
                        { name: "expiryAge", type: "uint256", internalType: "uint256" },
                        { name: "warningWindow", type: "uint256", internalType: "uint256" },
                    ],
                    outputs: [{ name: "", type: "bool", internalType: "bool" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "isRecentlyVerified",
                    inputs: [
                        { name: "student", type: "address", internalType: "address" },
                        { name: "maxAge", type: "uint256", internalType: "uint256" },
                    ],
                    outputs: [{ name: "", type: "bool", internalType: "bool" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "isVerified",
                    inputs: [{ name: "student", type: "address", internalType: "address" }],
                    outputs: [{ name: "", type: "bool", internalType: "bool" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "owner",
                    inputs: [],
                    outputs: [{ name: "", type: "address", internalType: "address" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "renounceOwnership",
                    inputs: [],
                    outputs: [],
                    stateMutability: "nonpayable",
                },
                {
                    type: "function",
                    name: "revokeVerification",
                    inputs: [{ name: "student", type: "address", internalType: "address" }],
                    outputs: [],
                    stateMutability: "nonpayable",
                },
                {
                    type: "function",
                    name: "totalVerified",
                    inputs: [],
                    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "transferFrom",
                    inputs: [
                        { name: "", type: "address", internalType: "address" },
                        { name: "", type: "address", internalType: "address" },
                        { name: "", type: "uint256", internalType: "uint256" },
                    ],
                    outputs: [],
                    stateMutability: "pure",
                },
                {
                    type: "function",
                    name: "transferOwnership",
                    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
                    outputs: [],
                    stateMutability: "nonpayable",
                },
                {
                    type: "function",
                    name: "usedEphemeralKeys",
                    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
                    outputs: [{ name: "", type: "bool", internalType: "bool" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "verifications",
                    inputs: [{ name: "", type: "address", internalType: "address" }],
                    outputs: [
                        { name: "verifiedAt", type: "uint256", internalType: "uint256" },
                        { name: "ephemeralPubkey", type: "bytes32", internalType: "bytes32" },
                        { name: "exists", type: "bool", internalType: "bool" },
                    ],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "verifier",
                    inputs: [],
                    outputs: [{ name: "", type: "address", internalType: "contract IVerifier" }],
                    stateMutability: "view",
                },
                {
                    type: "function",
                    name: "verifyAndMint",
                    inputs: [
                        { name: "proof", type: "bytes", internalType: "bytes" },
                        { name: "publicInputs", type: "bytes32[]", internalType: "bytes32[]" },
                    ],
                    outputs: [],
                    stateMutability: "nonpayable",
                },
                {
                    type: "event",
                    name: "OwnershipTransferred",
                    inputs: [
                        { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
                        { name: "newOwner", type: "address", indexed: true, internalType: "address" },
                    ],
                    anonymous: false,
                },
                {
                    type: "event",
                    name: "StudentReverified",
                    inputs: [
                        { name: "student", type: "address", indexed: true, internalType: "address" },
                        { name: "newTimestamp", type: "uint256", indexed: false, internalType: "uint256" },
                    ],
                    anonymous: false,
                },
                {
                    type: "event",
                    name: "StudentVerified",
                    inputs: [
                        { name: "student", type: "address", indexed: true, internalType: "address" },
                        { name: "ephemeralPubkey", type: "bytes32", indexed: false, internalType: "bytes32" },
                        { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
                    ],
                    anonymous: false,
                },
                {
                    type: "error",
                    name: "OwnableInvalidOwner",
                    inputs: [{ name: "owner", type: "address", internalType: "address" }],
                },
                {
                    type: "error",
                    name: "OwnableUnauthorizedAccount",
                    inputs: [{ name: "account", type: "address", internalType: "address" }],
                },
            ],
            inheritedFunctions: {},
        },
    },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
