// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

import "@openzeppelin/contracts/access/Ownable.sol";

interface IZeroKlueVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/**
 * @title ZeroKlue Proof Registry
 * @notice Prototype registry for wallets with a valid circuit proof
 * @dev Proof acceptance does not establish current student enrollment.
 */
contract ZeroKlue is Ownable {
    IZeroKlueVerifier public immutable verifier;
    uint256 private constant JWT_MODULUS_OFFSET = 0;
    uint256 private constant JWT_MODULUS_LIMBS = 18;
    uint256 private constant DOMAIN_BYTES_OFFSET = 18;
    uint256 private constant DOMAIN_BYTES_LENGTH = 64;
    uint256 private constant DOMAIN_LENGTH_INDEX = 82;
    uint256 private constant AUDIENCE_BYTES_OFFSET = 83;
    uint256 private constant AUDIENCE_BYTES_LENGTH = 80;
    uint256 private constant AUDIENCE_LENGTH_INDEX = 163;
    uint256 private constant EPHEMERAL_PUBKEY_INDEX = 164;
    uint256 private constant EPHEMERAL_EXPIRY_INDEX = 165;
    uint256 private constant JWT_EXPIRY_INDEX = 166;
    // ============ State Variables ============

    struct StudentVerification {
        uint256 verifiedAt;      // When verification was registered
        bytes32 ephemeralPubkey; // The ephemeral public key used
        bool exists;             // For balanceOf optimization
    }

    // Student address => their verification
    mapping(address => StudentVerification) public verifications;
    
    // Ephemeral pubkey => used (prevents same key twice)
    mapping(bytes32 => bool) public usedEphemeralKeys;

    // Fingerprints are keccak256(abi.encodePacked(the fixed public-input arrays)).
    // Owners must source keys from Google's JWKS and domains from approved institutions.
    mapping(bytes32 => bool) public trustedJwtKeyFingerprints;
    mapping(bytes32 => bool) public approvedDomainFingerprints;
    mapping(bytes32 => bool) public approvedAudienceFingerprints;
    
    // Total verified students (for stats)
    uint256 public totalVerified;

    // ============ Events ============

    event StudentVerified(
        address indexed student,
        bytes32 ephemeralPubkey,
        uint256 timestamp
    );
    
    event StudentReverified(
        address indexed student,
        uint256 newTimestamp
    );

    event TrustedJwtKeyUpdated(bytes32 indexed fingerprint, bool trusted);
    event ApprovedDomainUpdated(bytes32 indexed fingerprint, bool approved);
    event ApprovedAudienceUpdated(bytes32 indexed fingerprint, bool approved);

    // ============ Constructor ============

    constructor(address verifierAddress) Ownable(msg.sender) {
        require(verifierAddress != address(0), "Verifier address is zero");
        verifier = IZeroKlueVerifier(verifierAddress);
    }

    // ============ Core Functions ============

    /**
     * @notice Register the ephemeral key bound into a valid circuit proof
     * @dev The proof exposes the RSA modulus, Workspace hosted domain, and
     *      OAuth audience. The registry checks all three against owner-managed
     *      allowlists and rejects an expired JWT before accepting it.
     * @param proof UltraHonk proof generated by the checked-in circuit
     * @param publicInputs The circuit's 167 public inputs
     */
    function registerStudent(bytes calldata proof, bytes32[] calldata publicInputs) external {
        require(publicInputs.length == 167, "Invalid public input count");
        require(uint256(publicInputs[DOMAIN_LENGTH_INDEX]) > 0 && uint256(publicInputs[DOMAIN_LENGTH_INDEX]) <= DOMAIN_BYTES_LENGTH, "Invalid domain length");
        require(uint256(publicInputs[AUDIENCE_LENGTH_INDEX]) > 0 && uint256(publicInputs[AUDIENCE_LENGTH_INDEX]) <= AUDIENCE_BYTES_LENGTH, "Invalid audience length");
        require(uint256(publicInputs[EPHEMERAL_EXPIRY_INDEX]) > block.timestamp, "Ephemeral key expired");
        require(uint256(publicInputs[JWT_EXPIRY_INDEX]) > block.timestamp, "JWT expired");
        require(trustedJwtKeyFingerprints[_keyFingerprint(publicInputs)], "Untrusted JWT signing key");
        require(approvedDomainFingerprints[_domainFingerprint(publicInputs)], "Unapproved organization domain");
        require(approvedAudienceFingerprints[_audienceFingerprint(publicInputs)], "Unapproved OAuth audience");
        require(verifier.verify(proof, publicInputs), "Invalid proof");
        bytes32 ephemeralPubkey = publicInputs[EPHEMERAL_PUBKEY_INDEX];

        // 1. Check ephemeral key not already used
        require(!usedEphemeralKeys[ephemeralPubkey], "Ephemeral key already used");

        // 2. Check if reverifying (same student, different ephemeral key)
        bool isReverification = verifications[msg.sender].exists;

        // 3. Store verification with current timestamp
        verifications[msg.sender] = StudentVerification({
            verifiedAt: block.timestamp,
            ephemeralPubkey: ephemeralPubkey,
            exists: true
        });

        // 4. Mark ephemeral key as used
        usedEphemeralKeys[ephemeralPubkey] = true;

        // 5. Update counter and emit events
        if (!isReverification) {
            totalVerified++;
            emit StudentVerified(msg.sender, ephemeralPubkey, block.timestamp);
        } else {
            emit StudentReverified(msg.sender, block.timestamp);
        }
    }

    // ============ View Functions (Merchant-facing) ============

    /**
     * @notice Check if address is a verified student
     */
    function isVerified(address student) public view returns (bool) {
        return verifications[student].exists;
    }

    /**
     * @notice Check if verification is recent (within maxAge)
     */
    function isRecentlyVerified(address student, uint256 maxAge) 
        public 
        view 
        returns (bool) 
    {
        StudentVerification memory verification = verifications[student];
        
        if (!verification.exists) {
            return false;
        }
        
        return (block.timestamp - verification.verifiedAt) <= maxAge;
    }

    /**
     * @notice Get full verification details
     */
    function getVerification(address student) 
        public 
        view 
        returns (uint256 verifiedAt, bytes32 ephemeralPubkey, uint256 age) 
    {
        StudentVerification memory verification = verifications[student];
        require(verification.exists, "Not verified");
        
        verifiedAt = verification.verifiedAt;
        ephemeralPubkey = verification.ephemeralPubkey;
        age = block.timestamp - verification.verifiedAt;
    }

    /**
     * @notice Check if verification expires soon
     */
    function isExpiringSoon(
        address student,
        uint256 expiryAge,
        uint256 warningWindow
    ) public view returns (bool) {
        StudentVerification memory verification = verifications[student];
        
        if (!verification.exists) {
            return false;
        }
        
        uint256 age = block.timestamp - verification.verifiedAt;
        return age >= (expiryAge - warningWindow) && age < expiryAge;
    }

    // ============ NFT-like Functions (for compatibility) ============

    /**
     * @notice Returns 1 if verified, 0 if not (NFT balanceOf compatibility)
     */
    function balanceOf(address student) public view returns (uint256) {
        return verifications[student].exists ? 1 : 0;
    }

    /**
     * @notice Prevent transfers (soulbound NFT)
     */
    function transferFrom(address, address, uint256) public pure {
        revert("Soulbound: cannot transfer");
    }

    // ============ Admin Functions ============

    /**
     * @notice Approve or revoke a JWT RSA modulus fingerprint.
     * @dev Pass the 18 bytes32 public-input limbs at indices 0..17. Only
     *      approve fingerprints derived from Google's current published JWKS.
     */
    function setTrustedJwtKey(bytes32[18] calldata modulusLimbs, bool trusted) external onlyOwner {
        bytes32 fingerprint = keccak256(abi.encodePacked(modulusLimbs));
        trustedJwtKeyFingerprints[fingerprint] = trusted;
        emit TrustedJwtKeyUpdated(fingerprint, trusted);
    }

    /**
     * @notice Approve or revoke a domain fingerprint.
     * @dev Pass the 64 bytes32 public-input elements at indices 18..81; each
     *      element is an ASCII byte value or zero padding.
     */
    function setApprovedDomain(bytes32[64] calldata domainBytes, bool approved) external onlyOwner {
        bytes32 fingerprint = keccak256(abi.encodePacked(domainBytes));
        approvedDomainFingerprints[fingerprint] = approved;
        emit ApprovedDomainUpdated(fingerprint, approved);
    }

    /**
     * @notice Approve or revoke a Google OAuth client ID used as a JWT audience.
     * @dev Pass the 80 bytes32 public-input elements at indices 83..162.
     */
    function setApprovedAudience(bytes32[80] calldata audienceBytes, uint256 audienceLength, bool approved) external onlyOwner {
        require(audienceLength > 0 && audienceLength <= AUDIENCE_BYTES_LENGTH, "Invalid audience length");
        bytes32 fingerprint = keccak256(abi.encodePacked(audienceBytes, audienceLength));
        approvedAudienceFingerprints[fingerprint] = approved;
        emit ApprovedAudienceUpdated(fingerprint, approved);
    }

    /**
     * @notice Emergency revoke verification (only owner)
     */
    function revokeVerification(address student) external onlyOwner {
        require(verifications[student].exists, "Not verified");
        delete verifications[student];
        totalVerified--;
    }

    function _keyFingerprint(bytes32[] calldata publicInputs) private pure returns (bytes32) {
        bytes32[18] memory modulusLimbs;
        for (uint256 i = 0; i < JWT_MODULUS_LIMBS; i++) {
            modulusLimbs[i] = publicInputs[JWT_MODULUS_OFFSET + i];
        }
        return keccak256(abi.encodePacked(modulusLimbs));
    }

    function _domainFingerprint(bytes32[] calldata publicInputs) private pure returns (bytes32) {
        bytes32[64] memory domainBytes;
        for (uint256 i = 0; i < DOMAIN_BYTES_LENGTH; i++) {
            domainBytes[i] = publicInputs[DOMAIN_BYTES_OFFSET + i];
        }
        return keccak256(abi.encodePacked(domainBytes));
    }

    function _audienceFingerprint(bytes32[] calldata publicInputs) private pure returns (bytes32) {
        bytes32[80] memory audienceBytes;
        for (uint256 i = 0; i < AUDIENCE_BYTES_LENGTH; i++) {
            audienceBytes[i] = publicInputs[AUDIENCE_BYTES_OFFSET + i];
        }
        return keccak256(abi.encodePacked(audienceBytes, uint256(publicInputs[AUDIENCE_LENGTH_INDEX])));
    }
}
