/**
 * NoirJS Integration for ZeroKlue
 * 
 * Handles:
 * - Loading Noir circuit artifacts
 * - Generating ZK proofs in the browser
 * - Preparing inputs for smart contract verification
 * 
 * @see https://noir-lang.org/docs/tutorials/noirjs_app
 */

// TODO: Frontend Dev - Install these packages:
// pnpm add @noir-lang/noir_js @noir-lang/backend_barretenberg

export interface Credential {
  signature: string;        // EdDSA signature from backend (hex)
  nullifier_seed: string;   // Random seed for nullifier derivation
  issuer_pubkey_x: string;  // Issuer's public key X (hex)
  issuer_pubkey_y: string;  // Issuer's public key Y (hex)
  email_hash: string;       // Poseidon hash of email (hex)
  wallet: string;           // User's wallet address
}

export interface ProofResult {
  proof: Uint8Array;
  publicInputs: string[];
}

export interface ProofProgress {
  stage: 'loading' | 'witness' | 'proving' | 'done';
  progress: number; // 0-100
  message: string;
}

/**
 * Generate a ZK proof from a credential
 * 
 * This proves:
 * 1. User has a valid signature from ZeroKlue issuer
 * 2. The signature is bound to their wallet
 * 3. The nullifier derives from their email (prevents double-spend)
 * 
 * WITHOUT revealing:
 * - The actual email
 * - The signature
 * - The nullifier seed
 */
export async function generateProof(
  credential: Credential,
  onProgress?: (progress: ProofProgress) => void
): Promise<ProofResult> {
  
  onProgress?.({ stage: 'loading', progress: 10, message: 'Loading circuit...' });
  
  // Dynamic import to avoid loading heavy WASM on initial page load
  const [{ Noir }, { BarretenbergBackend }] = await Promise.all([
    import('@noir-lang/noir_js'),
    import('@noir-lang/backend_barretenberg'),
  ]);

  onProgress?.({ stage: 'loading', progress: 30, message: 'Initializing prover...' });

  // Load compiled circuit (generated by `nargo compile`)
  // TODO: Place compiled circuit JSON in public/circuits/zeroklue.json
  const circuitResponse = await fetch('/circuits/zeroklue.json');
  const circuit = await circuitResponse.json();

  const noir = new Noir(circuit);
  const backend = new BarretenbergBackend(circuit);

  onProgress?.({ stage: 'witness', progress: 50, message: 'Computing witness...' });

  // Prepare circuit inputs
  const inputs = {
    // Public inputs (will be visible on-chain)
    issuer_pubkey_x: credential.issuer_pubkey_x,
    issuer_pubkey_y: credential.issuer_pubkey_y,
    nullifier: computeNullifier(credential.nullifier_seed),
    wallet_address: walletToField(credential.wallet),
    
    // Private inputs (hidden from verifier)
    signature_r: credential.signature.slice(0, 66), // First 32 bytes
    signature_s: credential.signature.slice(66),    // Last 32 bytes
    email_hash: credential.email_hash,
  };

  // Generate witness (satisfying assignment)
  const { witness } = await noir.execute(inputs);

  onProgress?.({ stage: 'proving', progress: 70, message: 'Generating proof...' });

  // Generate the actual ZK proof (this is the slow part, ~10-15s)
  const proof = await backend.generateProof(witness);

  onProgress?.({ stage: 'done', progress: 100, message: 'Proof ready!' });

  return {
    proof: proof.proof,
    publicInputs: proof.publicInputs,
  };
}

/**
 * Compute nullifier from seed using Poseidon hash
 * Must match circuit computation exactly
 */
function computeNullifier(seed: string): string {
  // TODO: Use actual Poseidon hash
  // For now, placeholder - coordinate with ZK dev
  // See: https://github.com/zkpassport/poseidon2 for TS implementation
  return seed;
}

/**
 * Convert wallet address to field element
 */
function walletToField(wallet: string): string {
  // Remove 0x prefix and convert to field
  return BigInt(wallet).toString();
}

/**
 * Format proof for smart contract submission
 */
export function formatProofForContract(result: ProofResult): {
  proof: `0x${string}`;
  publicInputs: readonly bigint[];
} {
  return {
    proof: `0x${Buffer.from(result.proof).toString('hex')}` as `0x${string}`,
    publicInputs: result.publicInputs.map(BigInt),
  };
}
